# Generated by Django 4.2.7 on 2024-01-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(default='Default Description')),
                ('img', models.ImageField(blank=True, default='null', null=True, upload_to='categories')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10)),
                ('display_size', models.IntegerField()),
                ('camera', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('network', models.BooleanField()),
                ('smart', models.BooleanField()),
                ('battery', models.IntegerField()),
                ('image', models.ImageField(default='default_image.jpg', upload_to='products')),
                ('stock', models.IntegerField(default=3)),
                ('offer', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('offer_price', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.main_category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='main_app.product')),
            ],
        ),
    ]
