# Generated by Django 4.2.7 on 2024-01-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
