# Generated by Django 4.2.7 on 2024-01-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_main_category_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='img',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='categories'),
        ),
    ]
