# Generated by Django 4.2.7 on 2024-02-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_brand_description_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
