# Generated by Django 4.2.7 on 2023-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='descriptions',
            field=models.TextField(default='Default Description'),
        ),
    ]
