# Generated by Django 4.2.7 on 2024-01-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_product_offer_remove_product_offer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='storage',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
