# Generated by Django 4.2.7 on 2023-11-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_main_category_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='img',
            field=models.ImageField(default=None, upload_to='categories'),
        ),
    ]
