# Generated by Django 4.2.7 on 2024-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
