# Generated by Django 4.2.7 on 2023-11-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_main_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='img',
            field=models.ImageField(default='null', upload_to='categories'),
        ),
    ]
