# Generated by Django 4.2.4 on 2023-11-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_main_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featurephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=10)),
                ('display_size', models.IntegerField()),
                ('camera_resolution', models.CharField(max_length=20)),
                ('storage_capacity', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('network', models.BooleanField()),
                ('smart', models.BooleanField()),
                ('battery', models.IntegerField()),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.main_category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=10)),
                ('display_size', models.IntegerField()),
                ('camera_resolution', models.CharField(max_length=20)),
                ('storage_capacity', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('network', models.BooleanField()),
                ('smart', models.BooleanField()),
                ('battery', models.IntegerField()),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.main_category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
