# Generated by Django 4.2.7 on 2023-11-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_featurephone_smartphone_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurephone',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featurephone',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='featurephone',
            name='product_offer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='featurephone',
            name='stock',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='product_offer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='stock',
            field=models.IntegerField(default=3),
        ),
    ]
