# Generated by Django 4.2.7 on 2023-11-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_featurephone_deleted_featurephone_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurephone',
            old_name='camera_resolution',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='featurephone',
            old_name='product_offer',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='featurephone',
            old_name='storage_capacity',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='camera_resolution',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='product_offer',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='storage_capacity',
            new_name='storage',
        ),
        migrations.AlterField(
            model_name='featurephone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(),
        ),
    ]
