# Generated by Django 4.2.7 on 2023-11-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_camera_resolution_featurephone_camera_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Featurephone',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
