# Generated by Django 4.2.7 on 2023-12-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='phone',
        ),
    ]
