# Generated by Django 4.2.7 on 2024-02-14 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('valid', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('min_amount', models.IntegerField(null=True)),
            ],
        ),
    ]
