# Generated by Django 4.2.7 on 2024-01-24 04:32

from django.db import migrations
import gauth_app.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', gauth_app.manager.UserManager()),
            ],
        ),
    ]
