# Generated by Django 4.2.7 on 2023-12-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0002_rename_number_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='products'),
        ),
    ]
