# Generated by Django 4.2.7 on 2024-02-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_total', models.IntegerField(blank=True, default=0, null=True)),
                ('price_total', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gauth_app.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
