# Generated by Django 4.2.7 on 2024-01-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_product_storage_productvariant_storage'),
        ('gauth_app', '0004_alter_order_amount_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.productvariant'),
        ),
    ]
