# Generated by Django 4.2.7 on 2023-12-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0006_alter_customer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photo/profile.png', null=True, upload_to='profile_photo'),
        ),
    ]
