# Generated by Django 4.2.7 on 2024-02-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0007_order_details_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='price',
        ),
    ]
