# Generated by Django 4.2.7 on 2024-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0008_remove_order_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='payment_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
