# Generated by Django 4.2.7 on 2023-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0008_alter_customer_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
