# Generated by Django 4.2.7 on 2024-02-18 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0008_remove_order_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
