# Generated by Django 4.2.7 on 2023-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0009_remove_address_address_address_address_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='pin_code',
            new_name='pin',
        ),
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
