# Generated by Django 4.2.7 on 2024-02-18 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0009_customer_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
