# Generated by Django 4.2.7 on 2024-02-20 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gauth_app', '0011_customer_referral_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet_bal',
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
